[package]
name = "obs-scheduled-recordings"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
chrono = "0.4.34"
clap = { version = "4.5.38", features = ["derive"] }
obws = "0.14.0"
tokio = { version = "1.45.0", features = ["full"] }
